import Link from "next/link";
import { notFound } from "next/navigation";
import { getSupabaseServerClient } from "@/lib/supabase/server";

/**
 * The summary screen (2h) is the landing point after both the live flow's
 * reveal step and — eventually — the daily practice loop. It only ever
 * re-renders what `runRevealStep`/`submitPracticeGuess` (Tasks 7 and 8)
 * already persisted; it never re-runs the model.
 *
 * `goal`/`problem_type` are always NULL for `source: "practice"` rows —
 * Task 8's combined guess+reveal flow skips Task 5's structuring step
 * entirely for practice cases (see Task 8's report). This screen must not
 * assume those columns are populated just because live-sourced rows have
 * them; the "problem" section is only rendered when both are present.
 */
export default async function SolveSummaryPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await getSupabaseServerClient();

  const { data: solve } = await supabase
    .from("solves")
    .select(
      "source, goal, problem_type, guessed_category, revealed_category, tool_class, correct, why_it_fits"
    )
    .eq("id", id)
    .single();

  if (!solve) notFound();

  // A takeaway isn't generated by anything upstream of this task yet (no task
  // writes to the `takeaways` table), so this row may simply not exist. That's
  // an expected, not-yet-generated state, not an error — `maybeSingle` returns
  // null data instead of throwing on zero rows.
  const { data: takeaway } = await supabase
    .from("takeaways")
    .select("draft_text")
    .eq("solve_id", id)
    .maybeSingle();

  const restartHref =
    solve.source === "practice" ? "/practice/today" : `/solve/${id}/guess`;

  if (!solve.revealed_category || solve.correct === null) {
    return (
      <main>
        <h1>This solve isn&apos;t finished yet</h1>
        <p>Lock in a guess and see the reveal before checking the summary.</p>
        <Link href={restartHref}>Continue where you left off</Link>
      </main>
    );
  }

  const hasStructuredProblem = Boolean(solve.goal && solve.problem_type);

  return (
    <main>
      <h1>{solve.correct ? "You had it." : "Not quite."}</h1>

      {hasStructuredProblem ? (
        <section>
          <h2>The problem</h2>
          <p>
            <strong>Goal:</strong> {solve.goal}
          </p>
          <p>
            <strong>Problem type:</strong> {solve.problem_type}
          </p>
        </section>
      ) : null}

      <section>
        <h2>Your answer</h2>
        <p>
          You guessed <strong>{solve.guessed_category}</strong>. This is a{" "}
          <strong>{solve.revealed_category}</strong> problem.
        </p>
        {solve.tool_class ? (
          <p>
            Tool class: <strong>{solve.tool_class}</strong>
          </p>
        ) : null}
      </section>

      {solve.why_it_fits ? (
        <section>
          <h2>Why {solve.revealed_category} fits</h2>
          <p>{solve.why_it_fits}</p>
        </section>
      ) : null}

      {takeaway?.draft_text ? (
        <section aria-label="Takeaway">
          <h2>Your takeaway</h2>
          <p>{takeaway.draft_text}</p>
        </section>
      ) : null}

      <nav aria-label="What's next">
        <Link href="/solve/new">Solve another</Link>
        <Link href="/practice/today">Today&apos;s practice</Link>
        <Link href="/">Home</Link>
      </nav>
    </main>
  );
}
