-- Converts scenario_quiz_questions from reveal-the-answer format to 4-option
-- MCQ, matching general_quiz_questions' shape, per the practice-nav rework
-- that unified Quiz Time and Scenario Based Question into the same
-- difficulty -> 4-option-MCQ -> timer flow. Distractors were hand-written
-- (not the fixed `answer` reused as a distinct wrong option elsewhere) since
-- these are judgment questions with one clearly-correct approach; the 3
-- wrong options are plausible-but-wrong actions for the same scenario.

alter table scenario_quiz_questions add column if not exists options jsonb;
alter table scenario_quiz_attempts add column if not exists selected_answer text;
alter table scenario_quiz_attempts add column if not exists correct boolean;

update scenario_quiz_questions set options = '["Use AI to summarize the report.", "Read the full report line by line", "Skip the report and guess", "Print the report for the client to read"]'::jsonb where question_text = 'You receive a 40-page client report and have 10 minutes before a meeting. How could AI help you prepare quickly?';
update scenario_quiz_questions set options = '["Manually read all 500 comments one by one", "Use AI to group similar comments.", "Ignore the comments and assume you know", "Randomly sample 5 comments and stop there"]'::jsonb where question_text = 'You have 500 customer comments in Excel and need to understand the most common complaints. What approach would you use?';
update scenario_quiz_questions set options = '["Re-read every email in the thread yourself", "Ask your manager to repeat the whole thread verbally", "Ask AI to summarize the email thread and decisions.", "Guess the decision based on the subject line"]'::jsonb where question_text = 'Your manager sends you a long email thread and asks, “What did we finally decide?” How could AI help?';
update scenario_quiz_questions set options = '["Copy a generic template with no context", "Send the email without writing anything first", "Wait for the client to email first", "Give AI the meeting context and ask it to draft the email."]'::jsonb where question_text = 'You need to write a professional follow-up email after a client meeting. How would you use AI effectively?';
update scenario_quiz_questions set options = '["Ask AI to extract tasks, owners and deadlines.", "Leave the notes unorganized and hope people remember", "Assign every task to yourself", "Delete the notes after the meeting"]'::jsonb where question_text = 'You have meeting notes containing several tasks assigned to different people. How could AI help organize them?';
update scenario_quiz_questions set options = '["Manually scroll through every row to spot duplicates", "Use Excel''s Remove Duplicates or data-cleaning tools.", "Ignore duplicates since they don''t matter", "Delete the entire dataset and start over"]'::jsonb where question_text = 'Your Excel sheet contains duplicate customer records. What should you do to identify or remove them?';
update scenario_quiz_questions set options = '["Use the original technical jargon unchanged", "Tell the client to look it up themselves", "Avoid the topic entirely in the meeting", "Ask AI to explain it in plain language with an example."]'::jsonb where question_text = 'You need to explain a technical AI concept to a non-technical client. How could AI help you simplify it?';
update scenario_quiz_questions set options = '["Compare sales by month.", "Compare sales by employee name", "Guess based on the weather that month", "Only look at the most recent week"]'::jsonb where question_text = 'Your manager gives you sales data and asks which month performed best. What would you do first?';
update scenario_quiz_questions set options = '["Listen to the full recording at normal speed", "Use transcription and AI summarization.", "Ask a colleague to summarize from memory", "Skip the meeting notes entirely"]'::jsonb where question_text = 'You have a recorded meeting and don''t have time to listen to the full hour. How could technology help?';
update scenario_quiz_questions set options = '["Keep rebuilding the report manually every week", "Ask someone else to do it once", "Automate data collection and report creation.", "Stop sending the report altogether"]'::jsonb where question_text = 'You repeatedly create the same weekly status report using updated numbers. What could you automate?';
update scenario_quiz_questions set options = '["Read both documents side by side from memory", "Assume nothing changed between versions", "Only check the document titles", "Use an AI or document comparison tool."]'::jsonb where question_text = 'You need to compare two versions of a policy document. How could AI make this easier?';
update scenario_quiz_questions set options = '["Data cleaning.", "Predictive analytics", "Data visualization", "Statistical forecasting"]'::jsonb where question_text = 'You have customer names, email addresses and phone numbers in separate Excel columns. What type of task is this: data cleaning, analysis or prediction?';
update scenario_quiz_questions set options = '["Reuse last year''s agenda without changes", "Skip planning and improvise on the day", "Give AI the workshop goal and ask for agenda ideas.", "Ask attendees to write their own agenda"]'::jsonb where question_text = 'You need ideas for the agenda of a client workshop tomorrow. How could generative AI help?';
update scenario_quiz_questions set options = '["Manually scan every row for High Risk", "Sort alphabetically by customer name", "Delete all rows that aren''t High Risk", "Use Excel filters."]'::jsonb where question_text = 'You have a spreadsheet with thousands of rows and want to quickly find only “High Risk” cases. What Excel capability would help?';
update scenario_quiz_questions set options = '["Copy the entire report into the slides", "Ask AI to summarize it into five presentation points.", "Pick five random sentences from the report", "Ask the client to shorten it themselves"]'::jsonb where question_text = 'Your manager asks you to turn a detailed report into five presentation bullets. What could you ask AI to do?';
update scenario_quiz_questions set options = '["Write each of the 50 emails individually", "Send one identical email to all 50 clients", "Use templates plus mail merge or automation.", "Delay sending until you have more time"]'::jsonb where question_text = 'You have to send similar personalized emails to 50 clients. How might you reduce the manual work?';
update scenario_quiz_questions set options = '["Nod along and hope it becomes clear later", "Guess the meaning from context alone", "Ask the client to explain it again immediately", "Ask AI to explain the term with an example."]'::jsonb where question_text = 'A client uses a technical term you''ve never heard before during a call. How could you quickly understand it after the meeting?';
update scenario_quiz_questions set options = '["Use AI translation.", "Ask a random colleague who might know the language", "Ignore the email since it''s not in English", "Use only your own guesswork to translate it"]'::jsonb where question_text = 'You need to translate a client email from another language. What type of AI capability could help?';
update scenario_quiz_questions set options = '["Pie chart", "Line chart.", "Scatter plot with no time axis", "Single bar with the yearly total"]'::jsonb where question_text = 'You want to create a chart showing how monthly revenue has changed over one year. What type of chart would you choose?';
update scenario_quiz_questions set options = '["Read the entire contract page by page", "Ask the client to highlight the clauses", "Skip the search and assume there are none", "Search the PDF or ask a document AI tool."]'::jsonb where question_text = 'You have a PDF contract and need to locate all references to “termination.” What''s the quickest technology-assisted approach?';
update scenario_quiz_questions set options = '["Ask AI to review the tone.", "Send it immediately without checking", "Ask a friend outside the company to review it", "Rewrite it entirely from scratch with no feedback"]'::jsonb where question_text = 'You have written a client update but aren''t confident about its tone. How could AI help before you send it?';
update scenario_quiz_questions set options = '["Keep answering each question individually by email", "Tell employees to figure it out themselves", "An internal AI knowledge assistant or chatbot.", "Hold a weekly meeting to repeat the same answers"]'::jsonb where question_text = 'Your team keeps answering the same internal process questions repeatedly. What kind of AI solution might help?';
update scenario_quiz_questions set options = '["A verbatim transcript with no organization", "A single summary sentence with no detail", "The original audio recording only", "Structured meeting minutes."]'::jsonb where question_text = 'You need to convert messy meeting notes into structured minutes. What should you ask an AI assistant to produce?';
update scenario_quiz_questions set options = '["Use the AVERAGE formula.", "Add up all values by hand and divide manually", "Guess a reasonable-sounding number", "Use the COUNT formula instead"]'::jsonb where question_text = 'Your manager asks for the average value of 200 transactions in Excel. What should you use instead of calculating manually?';
update scenario_quiz_questions set options = '["No, CSV files cannot be opened in Excel", "Convert it to a PDF first", "Ask the sender to resend it as a Word file", "Yes. Open or import the CSV into Excel."]'::jsonb where question_text = 'You receive a CSV file but normally work in Excel. Can the data still be opened and analyzed?';
update scenario_quiz_questions set options = '["Ask AI to create a first draft or outline.", "Start from a completely blank slide with no plan", "Copy a competitor''s presentation directly", "Wait until the day of the presentation to start"]'::jsonb where question_text = 'You need a first draft of a client presentation but already know the key points. How could AI speed up the process?';
update scenario_quiz_questions set options = '["Predictive analytics", "Regression modeling", "Sentiment analysis.", "Data deduplication"]'::jsonb where question_text = 'You want to know whether customer complaints are mostly positive, negative or neutral. What AI technique could help?';
update scenario_quiz_questions set options = '["Treat each spelling as a different city", "Delete all rows mentioning Delhi", "Ignore the inconsistency since it looks minor", "Standardize and clean the data."]'::jsonb where question_text = 'You have inconsistent entries such as “Delhi,” “New Delhi,” and “DELHI” in your dataset. What needs to happen before analysis?';
update scenario_quiz_questions set options = '["Automate the repetitive data transfer.", "Keep copying it manually every week", "Stop producing the second spreadsheet", "Hire someone new just for this task"]'::jsonb where question_text = 'Your team manually copies information from one spreadsheet to another every Friday. What should you consider automating?';
update scenario_quiz_questions set options = '["Use it immediately since AI is usually right", "Round the number to make it sound better", "Verify the statistic and its source.", "Remove the statistic instead of checking it"]'::jsonb where question_text = 'An AI tool gives you a statistic for a client presentation. What should you do before using it?';

update scenario_quiz_questions set options = '["Read every complaint individually with no grouping", "Use AI to categorize or cluster similar complaints and identify common themes.", "Ignore the complaints since there are too many", "Ask each customer to resubmit a shorter complaint"]'::jsonb where question_text = 'Your client has 10,000 customer complaints and wants to understand the major reasons customers are unhappy. How would you approach this using AI?';
update scenario_quiz_questions set options = '["Let it answer from general internet knowledge", "Have it guess based on common HR practices elsewhere", "Connect it to approved company HR policies and documents.", "Give it access to all employee personal files"]'::jsonb where question_text = 'Your manager wants a chatbot that can answer employee questions using company HR policies. What information should the chatbot use as its knowledge source?';
update scenario_quiz_questions set options = '["Use it anyway since AI is usually accurate", "Remove the number and leave a blank space", "Ask AI to make up a plausible source", "Don''t use it until you verify it against the original report."]'::jsonb where question_text = 'AI summarizes a financial report but mentions a number you cannot find. What should you do next?';
update scenario_quiz_questions set options = '["Use AI to summarize calls and automation to update relevant CRM fields.", "Keep updating CRM manually after every call", "Stop updating CRM records altogether", "Have a separate team re-type notes from scratch"]'::jsonb where question_text = 'Your sales team spends hours manually updating CRM records after calls. Where could AI or automation fit?';
update scenario_quiz_questions set options = '["Buy the most expensive AI tool available", "Identify the actual business problem.", "Copy exactly what the competitor is doing", "Agree immediately and pick a tool the same day"]'::jsonb where question_text = 'A client says, “We want AI because our competitors are using it.” What should you understand first?';
update scenario_quiz_questions set options = '["Answer emails in the order they arrive with no sorting", "Use AI to classify and prioritize emails, while humans handle important cases.", "Let AI reply to every email with no human review", "Ignore lower-priority emails permanently"]'::jsonb where question_text = 'Your team receives hundreds of support emails daily. How could AI help prioritize them?';
update scenario_quiz_questions set options = '["Only the customers'' names and contact details", "Random data unrelated to customer activity", "Only data from customers who already left", "Historical customer behavior and churn data."]'::jsonb where question_text = 'Your client wants to predict which customers may stop using its service. What historical data would you need?';
update scenario_quiz_questions set options = '["Data cleaning", "Forecasting or predictive analytics.", "Sentiment analysis", "Data deduplication"]'::jsonb where question_text = 'You have five years of sales data and need to estimate next quarter. What type of analytics problem is this?';
update scenario_quiz_questions set options = '["Let AI make the final hiring decisions alone", "Reject all résumés and start a new search", "AI can organize relevant résumés, but humans should make important hiring decisions.", "Have AI interview candidates without human involvement"]'::jsonb where question_text = 'A recruitment team receives 2,000 résumés for 20 positions. How could AI assist safely?';
update scenario_quiz_questions set options = '["Rely on the AI''s general training knowledge only", "Manually paste every document into every question", "Use a public chatbot with no company data connected", "Use a company knowledge base with RAG."]'::jsonb where question_text = 'You want an AI assistant to answer specifically from your organization''s documents. What setup would you recommend?';
update scenario_quiz_questions set options = '["Read invoices, extract fields, validate information and enter approved data into the ERP.", "Fully automate approval with no validation step", "Keep entering every invoice manually as before", "Automate only the filing, not the data entry"]'::jsonb where question_text = 'A client wants to automate invoice processing. Which parts could be automated?';
update scenario_quiz_questions set options = '["Let AI respond to every complaint with no oversight", "Use human review for sensitive or high-risk complaints.", "Stop responding to complaints automatically at all", "Only review complaints from long-time customers"]'::jsonb where question_text = 'Customer service wants AI to respond to every complaint automatically. What risk should you consider?';
update scenario_quiz_questions set options = '["Accept the summary as final without changes", "Stop using AI for meeting summaries entirely", "Improve the instructions and give AI a full, clear transcript.", "Ask AI to guess what decisions were likely made"]'::jsonb where question_text = 'Your AI meeting summary misses important decisions. How would you improve it?';
update scenario_quiz_questions set options = '["Upload the documents since AI tools are generally safe", "Ask the client for permission after uploading", "Remove only the client''s name before uploading", "Check company privacy and security policies."]'::jsonb where question_text = 'Your team wants to upload confidential client documents to a public AI tool. What should you check first?';
update scenario_quiz_questions set options = '["Write a unique email for each of the 100,000 customers", "Use customer segments, AI-generated templates and automation.", "Send the exact same email to everyone", "Only email customers who reply first"]'::jsonb where question_text = 'Marketing wants personalized emails for 100,000 customers. How could AI help?';
update scenario_quiz_questions set options = '["Always use AI regardless of complexity", "Avoid AI and Excel, do it by hand", "Use the simplest technology that solves the problem.", "Choose whichever tool is newest"]'::jsonb where question_text = 'A client asks whether they need AI when an Excel formula could solve the problem. How would you decide?';
update scenario_quiz_questions set options = '["Start building immediately with default metrics", "Include every metric available in the data", "Ask what decisions it should help make and which metrics matter.", "Ask a different team to define the requirements"]'::jsonb where question_text = 'A manager says, “Build me a dashboard,” with no other details. What should you ask?';
update scenario_quiz_questions set options = '["Fill in random locations to complete the dataset", "Ignore the missing rows and analyze the rest as-is", "Investigate and clean missing data before strong conclusions.", "Delete the location column entirely"]'::jsonb where question_text = '25% of sales rows are missing customer locations. What should you do before location analysis?';
update scenario_quiz_questions set options = '["Ask a general AI chatbot with no company data", "Assume it was due to the weather", "Analyze actual business data and possible causes.", "Wait for the next quarter to see if it recovers"]'::jsonb where question_text = 'Your client wants to know why sales dropped. Why isn''t asking a chatbot enough?';
update scenario_quiz_questions set options = '["Turn off the categorization feature permanently", "Ignore the errors since AI is mostly right", "Manually recategorize every email every day instead", "Review wrong examples, category definitions, prompts or training data, and performance."]'::jsonb where question_text = 'An AI system categorizes emails incorrectly. What would you investigate?';
update scenario_quiz_questions set options = '["Assume it can''t be automated and continue as-is", "Automate it immediately without reviewing the process", "Map the process and compare automation cost with time and value saved.", "Hire another person to help collect it manually"]'::jsonb where question_text = 'Your team spends two hours every morning collecting data from five systems. How would you assess automation?';
update scenario_quiz_questions set options = '["Upload the feedback as-is to any AI tool", "Remove or mask personal information and use an approved secure AI system.", "Delete all feedback that contains personal information", "Share it only with the client, not with AI"]'::jsonb where question_text = 'Customer feedback contains names and phone numbers. What should happen before using AI?';
update scenario_quiz_questions set options = '["Build the most advanced AI dashboard possible", "Say no since dashboards don''t need AI", "Assume they want a copy of a competitor''s dashboard", "Clarify the business goal instead of assuming AI is required."]'::jsonb where question_text = 'An executive asks for an “AI dashboard.” How would you clarify the need?';
update scenario_quiz_questions set options = '["Let employees use any AI tool they prefer", "Ban all AI tools across the organization", "Use approved tools, access controls, data policies and employee training.", "Only train the IT department on AI use"]'::jsonb where question_text = 'Your organization wants employees to use generative AI safely. What controls could help?';
update scenario_quiz_questions set options = '["Only the total transaction volume per month", "Customer satisfaction survey results", "Employee attendance records", "Historical transactions, especially known fraud and legitimate transactions."]'::jsonb where question_text = 'Your client wants AI to identify fraudulent transactions. What data would help?';
update scenario_quiz_questions set options = '["Only the lead''s name and email address", "Random assignment of scores", "The salesperson''s personal opinion alone", "Signals such as activity, past purchases, company details and engagement."]'::jsonb where question_text = 'A sales manager wants to score leads by likelihood of buying. What inputs could be used?';
update scenario_quiz_questions set options = '["This is a bug and AI should be abandoned", "Always trust the first answer given", "Ask the exact same question repeatedly until it matches", "LLM outputs can vary; use clearer prompts, controlled settings and trusted sources."]'::jsonb where question_text = 'An AI assistant gives different answers to similar questions. Why, and how can you reduce it?';
update scenario_quiz_questions set options = '["Intelligent document processing or OCR plus AI extraction.", "Manually retype every invoice into a spreadsheet", "Ask vendors to resend invoices in one fixed format", "Only process invoices under a certain amount"]'::jsonb where question_text = 'You need AI to extract fields from thousands of invoices with different layouts. What capability would you use?';
update scenario_quiz_questions set options = '["Save the raw audio file directly into CRM", "Skip CRM updates for shorter calls", "Have agents write summaries from memory at day''s end", "Transcribe, summarize, extract key information, check when needed, then update CRM."]'::jsonb where question_text = 'Your company wants every customer call summarized and saved to CRM. What workflow makes sense?';
update scenario_quiz_questions set options = '["Publish it since AI reports are usually accurate", "Verify important claims against reliable sources.", "Remove all numbers from the report", "Ask the client to verify it themselves after sending"]'::jsonb where question_text = 'An AI-generated client report has no sources. What should you do before sharing?';

update scenario_quiz_questions set options = '["Use risk scores and thresholds, with human review for uncertain or high-impact cases.", "Automatically reject every flagged transaction with no review", "Ignore suspicious transactions to avoid blocking customers", "Let each branch manager decide individually with no system"]'::jsonb where question_text = 'A bank wants AI to automatically reject suspicious transactions, but false positives could block legitimate customers. How would you design the decision process?';
update scenario_quiz_questions set options = '["Replace the agents immediately to cut costs", "Study the work first and identify tasks AI can safely automate or assist.", "Assume AI cannot help and keep everything manual", "Automate the highest-paid roles first regardless of task fit"]'::jsonb where question_text = 'A client wants to replace 50% of customer-service agents with AI because costs are high. How would you evaluate it?';
update scenario_quiz_questions set options = '["Deploy it immediately since 90% is a strong score", "Remove that employee group from the dataset entirely", "Don''t deploy it blindly. Investigate bias and performance across groups first.", "Lower the accuracy target instead of investigating"]'::jsonb where question_text = 'An attrition model is 90% accurate but performs poorly for one employee group. Would you deploy it?';
update scenario_quiz_questions set options = '["Give the assistant access to all documents equally", "Turn off search for confidential documents entirely", "Ask employees not to search for sensitive terms", "Keep document permissions and access controls in the AI system."]'::jsonb where question_text = 'An internal AI assistant searches confidential documents with different permissions. How do you prevent unauthorized access?';
update scenario_quiz_questions set options = '["Let AI approve or reject loans with no human review", "Base decisions only on the applicant''s postal code", "Skip regulatory review since AI is faster", "Check fairness, explainability, privacy, regulation, data quality and human oversight."]'::jsonb where question_text = 'A client wants AI to decide who receives loans. What risks and controls matter?';
update scenario_quiz_questions set options = '["Let the bot keep answering since customers rarely notice", "Turn off the refund topic in the bot with no fix", "Ground it in approved policies, test it, and send uncertain cases to humans.", "Give the bot more general internet knowledge instead"]'::jsonb where question_text = 'Your AI support bot confidently gives incorrect refund information. How would you reduce this?';
update scenario_quiz_questions set options = '["Start the AI project immediately on the messiest data", "Pick only the CRM data and ignore the rest", "Ask leadership to lower their expectations instead", "Integrate, clean and govern the data first."]'::jsonb where question_text = 'Customer data is spread across CRM, Excel, emails and ERP. Leadership wants AI insights. What first?';
update scenario_quiz_questions set options = '["Define use cases, users, data, permissions and success metrics.", "Start building immediately without any planning", "Buy the largest AI model available regardless of fit", "Give it access to every system on day one"]'::jsonb where question_text = 'An executive wants “our own ChatGPT trained on all company information.” How do you turn this into requirements?';
update scenario_quiz_questions set options = '["Ask investigators to review all flagged transactions anyway", "Lower the flagging rate until it matches capacity exactly", "Randomly select which flagged transactions get reviewed", "Prioritize alerts using risk levels and available investigation capacity."]'::jsonb where question_text = 'A fraud model flags 20% of transactions, but investigators can review only 2%. How would you redesign it?';
update scenario_quiz_questions set options = '["Combine all client data into one shared model", "Let any consultant access any client''s past project data", "Skip confidentiality since it''s for internal use only", "Separate client data and enforce strict access and privacy controls."]'::jsonb where question_text = 'A consulting team wants AI to use previous projects for recommendations. How do you protect client confidentiality?';
update scenario_quiz_questions set options = '["Mandate use with no explanation or support", "Assume the model itself must be technically wrong", "Replace the model with a simpler one automatically", "Usability, trust, workflow fit, training and incentives."]'::jsonb where question_text = 'An AI model is technically excellent but employees refuse to use it. What would you investigate?';
update scenario_quiz_questions set options = '["Not fully. The business needs actions tied to the prediction.", "Yes, accurate predictions alone are always enough value", "No, the model should be discarded entirely", "Yes, as long as the report looks professional"]'::jsonb where question_text = 'Churn predictions are accurate but the business doesn''t know what action to take. Is the model delivering value?';
update scenario_quiz_questions set options = '["Use the historical data exactly as-is since it''s real data", "Test historical data for bias and keep appropriate human oversight.", "Remove human oversight to make the process more objective", "Ignore bias concerns since the model is automated"]'::jsonb where question_text = 'Historical hiring data may contain bias. How should an AI screening system be approached?';
update scenario_quiz_questions set options = '["Always build custom regardless of cost or timeline", "Always buy off-the-shelf regardless of fit", "Cost, customization, speed, security, maintenance, skills and strategic importance.", "Whichever option the vendor recommends"]'::jsonb where question_text = 'A client asks whether to build an AI solution or buy a product. What factors matter?';
update scenario_quiz_questions set options = '["Collect as much personal data as possible for accuracy", "Skip consent since the data improves the product", "Share the data with other business units freely", "Collect only necessary data, get proper consent and protect it."]'::jsonb where question_text = 'A recommendation system is accurate but needs lots of personal data. How do you balance privacy?';
update scenario_quiz_questions set options = '["The system may have lacked validation, fraud controls, monitoring or human checkpoints.", "The AI model must have been too accurate", "Automation itself is always the root cause", "The invoices were simply too large in number"]'::jsonb where question_text = 'Automated invoice approvals later allow fraud. What may have gone wrong?';
update scenario_quiz_questions set options = '["Only measure the number of daily logins", "Measure task completion, accuracy, time saved, quality, adoption and user satisfaction.", "Only measure how much the tool cost to build", "Only measure how many features were shipped"]'::jsonb where question_text = 'How should leadership measure whether a generative-AI assistant is successful beyond number of users?';
update scenario_quiz_questions set options = '["The model must have been broken from the start", "Fraud simply stopped happening as often", "Real-world patterns may have changed; investigate model or data drift.", "The accuracy drop is likely a reporting error only"]'::jsonb where question_text = 'A bank fraud model worked for two years but accuracy falls. What might have changed?';
update scenario_quiz_questions set options = '["Rely fully on AI summaries with no legal review", "Stop using AI for contracts entirely with no alternative", "Only review contracts that are unusually long", "Let AI assist, but require human review for important clauses and decisions."]'::jsonb where question_text = 'An LLM summarizes legal contracts but sometimes misses unusual clauses. What is a safer workflow?';
update scenario_quiz_questions set options = '["Manually update the chatbot''s answers every day", "Connect it to only one of the 15 systems", "Build reliable integrations and a trusted information layer.", "Launch first and fix integrations after complaints arrive"]'::jsonb where question_text = 'A chatbot needs information from 15 systems that change often. What should happen before launch?';
update scenario_quiz_questions set options = '["Yes, 95% is always good enough to launch", "No, only 100% accuracy is ever acceptable", "It depends on the consequences and types of the remaining errors.", "It depends only on how long development took"]'::jsonb where question_text = 'Your AI system is 95% accurate. Is that good enough to launch?';
update scenario_quiz_questions set options = '["Treat it exactly like a support ticket system", "Let AI prioritize patients with no human review", "Skip validation since speed matters most in hospitals", "Medical decisions need stronger safety, privacy, validation and human oversight."]'::jsonb where question_text = 'A hospital wants AI to prioritize patient requests. Why is this different from support tickets?';
update scenario_quiz_questions set options = '["No decisions need human review if AI is accurate", "Only decisions under a very small dollar amount", "High-impact, uncertain, disputed or unusual decisions.", "Only decisions that are simple and low-risk"]'::jsonb where question_text = 'An insurer wants AI to write claim decisions and send them automatically. Where should humans review?';
update scenario_quiz_questions set options = '["Pick whichever five are easiest to build", "Pick the five most expensive-sounding projects", "Let each department pick one project regardless of value", "Business value, feasibility, risk, data readiness and effort or cost."]'::jsonb where question_text = 'You have 100 AI use cases but budget for five. How should you prioritize?';
update scenario_quiz_questions set options = '["The investment was not tied to a valuable problem and measurable ROI.", "AI projects always take this long to show value", "The client simply chose the wrong AI vendor", "Ten minutes per month is actually a strong result"]'::jsonb where question_text = 'A client spends ₹10 crore on AI that saves only 10 minutes per month. What went wrong?';
update scenario_quiz_questions set options = '["Trust employees to remember to check informally", "Ban AI analysis from being used in presentations", "Add sources, review steps, approval rules and accountability into the workflow.", "Only address it if a client complains"]'::jsonb where question_text = 'Employees copy AI analysis into client presentations without checking it. How would you redesign the process?';
update scenario_quiz_questions set options = '["98% is high enough, no changes are needed", "Turn off the assistant entirely with no replacement", "Only fix the errors after regulators complain", "Add stronger controls, human review and restricted automation for high-risk outputs."]'::jsonb where question_text = 'An AI assistant is 98% correct but the 2% errors could cause regulatory trouble. What should change?';
update scenario_quiz_questions set options = '["Give the agent full access to move faster", "Let the agent act with no logging or limits", "Minimum permissions, approval checkpoints, logs, action limits and an emergency stop.", "Only review its actions once a year"]'::jsonb where question_text = 'An AI agent can read emails, update CRM, schedule meetings and send responses. What safeguards are needed?';
update scenario_quiz_questions set options = '["Let each department continue choosing independently", "Ban all departments from using AI tools", "Standardize only on cost, ignoring security", "Centralized AI governance with approved tools, standards, ownership, monitoring and shared policies."]'::jsonb where question_text = 'Different departments deploy many AI tools and costs/security risks rise. What governance is needed?';
update scenario_quiz_questions set options = '["Promise the 30% target without a plan", "Apply the same AI tool across every department", "Focus only on cutting headcount to hit the number", "Break the goal into workflows, find bottlenecks, identify AI opportunities and define measurable outcomes."]'::jsonb where question_text = 'A CEO wants AI to make the organization 30% more productive. How do you turn this into solvable problems?';

-- Every row should now have exactly 4 options; enforce going forward.
alter table scenario_quiz_questions add constraint scenario_quiz_options_shape check (options is null or (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4));
